name: Deploy Cloud Functions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock pandas numpy faker
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest

  deploy_functions:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      CONSOLIDATE_MASTERS_FUNCTION: ${{ secrets.CONSOLIDATE_MASTERS_FUNCTION }}
      CONSOLIDATE_MASTERS_BUCKET: ${{ secrets.CONSOLIDATE_MASTERS_BUCKET }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Verify authentication
        run: |
          echo "Checking authentication..."
          gcloud auth list
          gcloud config list project
          echo "Current project: $(gcloud config get-value project)"
      
      - name: Deploy consolidate_masters function
        run: |
          cd cloud_functions/consolidate_masters
          chmod +x deploy.sh
          ./deploy.sh
      
      - name: Deploy generate_customers_daily function
        run: |
          cd cloud_functions/generate_customers_daily
          chmod +x deploy.sh
          ./deploy.sh
      
      - name: Deploy generate_products_daily function
        run: |
          cd cloud_functions/generate_products_daily
          chmod +x deploy.sh
          ./deploy.sh
      
      - name: Deploy generate_suppliers_daily function
        run: |
          cd cloud_functions/generate_suppliers_daily
          chmod +x deploy.sh
          ./deploy.sh
